//! Shellshare CLI client - Share your terminal session
//!
//! This module provides the client functionality for streaming terminal
//! output to a shellshare server.

mod crypto;
mod screen;
mod script;
mod ws;

use std::io::{self, IsTerminal, Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use crate::protocol::TermSize;
use qrcode::{render::unicode, QrCode};
use rand::Rng;

/// Get the current terminal size using ioctl (TIOCGWINSZ) via `term_size`.
/// Falls back to 80x24 when not attached to a terminal.
#[allow(clippy::cast_possible_truncation)] // Terminal dimensions always fit in u16
fn get_terminal_size() -> TermSize {
    term_size::dimensions()
        .map(|(cols, rows)| TermSize {
            cols: cols as u16,
            rows: rows as u16,
        })
        .unwrap_or_default()
}

/// Client configuration arguments
pub struct ClientArgs {
    pub server: String,
    /// URL viewers should use when it differs from the broadcast URL
    /// (e.g. a tunnel in front of the local server); the share link is
    /// printed with this, while the transport still talks to `server`
    pub display_server: Option<String>,
    pub room: Option<String>,
    pub password: Option<String>,
    /// Print machine-readable JSON events to stdout instead of prose
    pub json: bool,
    /// Command to run instead of an interactive shell (`shellshare exec`);
    /// the broadcast ends when it exits and its exit code is propagated
    pub exec: Option<Vec<String>>,
    /// Viewer color theme, already validated against `themes::names()`
    pub theme: Option<String>,
    /// End-to-end encrypt the broadcast (the default). When false the
    /// terminal is sent in plaintext - for viewers on plain HTTP, where
    /// browsers can't decrypt
    pub encrypt: bool,
}

/// Environment variable carrying the live broadcast's share URL into the
/// spawned shell, so `shellshare status` can re-print it from inside the
/// session. Kept in memory only - never written to disk.
pub const ENV_URL: &str = "SHELLSHARE_URL";
/// Environment variable carrying the live broadcast's room name.
pub const ENV_ROOM: &str = "SHELLSHARE_ROOM";

/// The live session details exported into the spawned shell's environment.
pub struct SessionEnv<'a> {
    pub url: &'a str,
    pub room: &'a str,
}

/// Generate a random 18-character alphanumeric room ID
fn generate_room_id() -> String {
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = rand::thread_rng();

    // Exactly 18 chars: the viewer recognizes auto-generated ids by this
    // length to keep them out of the tab title (isAutoGeneratedRoom in
    // templates/room.html), so the length must stay in lockstep.
    (0..18)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

/// Get the default password (MAC address as integer, like Python's `uuid.getnode()`)
fn get_default_password() -> String {
    if let Ok(Some(mac)) = mac_address::get_mac_address() {
        // Convert MAC address bytes to an integer (like Python's uuid.getnode())
        let bytes = mac.bytes();
        let mut value: u64 = 0;
        for &byte in &bytes {
            value = (value << 8) | u64::from(byte);
        }
        value.to_string()
    } else {
        // Fallback to a random value if MAC address is unavailable
        let mut rng = rand::thread_rng();
        rng.gen::<u64>().to_string()
    }
}

/// Whether browsers will treat the share link as a secure context.
/// `WebCrypto` (which the viewer needs to decrypt) only exists on https
/// pages, localhost, and loopback addresses.
///
/// Sibling loopback logic lives in `main.rs`'s `serve()`, but operates
/// on the raw `--host` arg (no scheme, plus wildcard detection), so the
/// two intentionally don't share a parser - keep their notions of
/// "loopback" consistent if either changes.
fn is_secure_context_url(base: &str) -> bool {
    let Some(rest) = base.strip_prefix("http://") else {
        return true; // https
    };
    let authority = rest.split('/').next().unwrap_or(rest);
    // Strip the port; IPv6 hosts are bracketed in URLs
    let host = authority.strip_prefix('[').map_or_else(
        || authority.rsplit_once(':').map_or(authority, |(h, _)| h),
        |h| h.split(']').next().unwrap_or(h),
    );
    let host = host.to_ascii_lowercase();
    host == "localhost"
        || host.ends_with(".localhost")
        || host
            .parse::<std::net::IpAddr>()
            .is_ok_and(|ip| ip.is_loopback())
}

/// Normalize server URL (ensure it has a scheme, strip trailing slashes)
fn normalize_server_url(server: &str) -> String {
    let server = if server.contains("://") {
        server.to_string()
    } else {
        format!("http://{server}")
    };
    server.trim_end_matches('/').to_string()
}

/// Emit one machine-readable event line on stdout (the `--json` contract:
/// whole JSON objects, one per line, flushed immediately so a pipe reader
/// sees the share URL before any terminal output follows).
fn emit_json(event: &serde_json::Value) {
    println!("{event}");
    let _ = io::stdout().flush();
}

/// Render a compact terminal QR code for the share URL. Failure should
/// never prevent a broadcast; the plain link remains the source of truth.
fn render_qr_code(url: &str) -> Option<String> {
    QrCode::new(url.as_bytes())
        .ok()
        .map(|code| code.render::<unicode::Dense1x2>().build())
}

/// Write the phone-scannable QR block for `url`, prefixed by an invitation
/// line. Best-effort: a QR render failure leaves the plain link as the
/// source of truth and prints nothing.
fn write_qr_code<W: Write>(writer: &mut W, url: &str) {
    if let Some(qr) = render_qr_code(url) {
        let _ = writeln!(writer);
        let _ = writeln!(writer, "Scan this QR code with your phone:");
        let _ = writeln!(writer, "{qr}");
    }
}

fn emit_human_sharing_message<W: Write>(writer: &mut W, share_url: &str, show_qr: bool) {
    let _ = writeln!(writer, "Sharing terminal in {share_url}");

    if show_qr {
        write_qr_code(writer, share_url);
    }

    let _ = writer.flush();
}

/// `shellshare status`: re-print the link (and QR) for the broadcast this
/// terminal is part of. The share URL is read from the `SHELLSHARE_URL`
/// environment variable that the broadcaster exports into the shell it
/// spawns, so this works only from inside a live shellshare session - and
/// without anything having been written to disk. Returns the exit code:
/// 0 when a session is found, 1 otherwise.
pub fn status(json: bool) -> i32 {
    let url = std::env::var(ENV_URL).ok().filter(|u| !u.is_empty());
    let Some(url) = url else {
        if json {
            // Mirror the --json contract: errors go to stderr, exit non-zero.
            eprintln!("ERROR: not inside a shellshare session");
        } else {
            eprintln!(
                "Not inside a shellshare session. Run `shellshare` first, then \
                 `shellshare status` from within the shared shell to see the link."
            );
        }
        return 1;
    };

    if json {
        let room = std::env::var(ENV_ROOM).ok();
        emit_json(&serde_json::json!({ "url": url, "room": room }));
        return 0;
    }

    let mut stdout = io::stdout();
    let _ = writeln!(stdout, "Sharing this terminal at {url}");
    if stdout.is_terminal() {
        write_qr_code(&mut stdout, &url);
    }
    let _ = stdout.flush();
    0
}

/// Run the shellshare client. Returns the exit code to propagate: the
/// child command's status for `exec`, otherwise 0.
pub fn run(args: ClientArgs) -> Result<i32, Box<dyn std::error::Error>> {
    let server = normalize_server_url(&args.server);
    let share_base = args
        .display_server
        .map_or_else(|| server.clone(), |s| normalize_server_url(&s));
    let room = args.room.unwrap_or_else(generate_room_id);
    let password = args.password.unwrap_or_else(get_default_password);

    // Build room path (r/{room})
    let room_path = format!("r/{room}");

    // Encrypted by default. The key goes only into the printed link's
    // #fragment - browsers never send fragments, so the server cannot
    // see it. Derived from this machine and the room name, so a named
    // room keeps one reusable link across restarts. --disable-encryption
    // drops to plaintext for viewers on plain HTTP (no WebCrypto there)
    let (cipher, share_url) = if args.encrypt {
        let (cipher, key) = crypto::Encryptor::for_room(&room);
        (Some(cipher), format!("{share_base}/{room_path}#{key}"))
    } else {
        (None, format!("{share_base}/{room_path}"))
    };
    if args.encrypt {
        if !is_secure_context_url(&share_base) {
            eprintln!(
                "WARNING: viewers can only decrypt on https or localhost; \
                 the link below is plain http, so browsers will refuse. \
                 For sharing over a plain-HTTP local network, run with \
                 --disable-encryption."
            );
        }
    } else {
        eprintln!(
            "WARNING: --disable-encryption is set; this broadcast is NOT \
             encrypted, so the server and anyone on the network can read \
             the terminal."
        );
    }

    // Connecting claims the room (or fails on a password mismatch), so
    // a broadcast that can never work is reported before the terminal
    // is handed over to the shell. Failures must propagate (not exit):
    // the caller may hold a tunnel whose cleanup an exit would skip
    let size = get_terminal_size();
    let transport =
        ws::Transport::connect(&server, &room_path, &password, size, args.theme, cipher)?;

    // Ctrl+C only flips the flag; the sending thread owns the transport
    // and performs cleanup (flush, room deletion) when it stops
    let running = Arc::new(AtomicBool::new(true));
    let running_clone = running.clone();
    ctrlc::set_handler(move || {
        running_clone.store(false, Ordering::SeqCst);
    })?;

    if args.json {
        emit_json(&serde_json::json!({
            "event": "sharing",
            "url": share_url,
            "room": room,
            "server": server,
            "encrypted": args.encrypt,
        }));
    }

    // Pipe/redirect into bare shellshare -> relay stdin verbatim; a TTY
    // (a human) or `exec` (an explicit command) spawns a PTY instead.
    let stream_mode = args.exec.is_none() && !io::stdin().is_terminal();

    let exit_code = if stream_mode {
        // Stream mode - prose goes to stderr (stdout may be piped onward)
        if !args.json {
            let mut stderr = io::stderr();
            let show_qr = stderr.is_terminal();
            emit_human_sharing_message(&mut stderr, &share_url, show_qr);
        }

        // Read from stdin, tee to stdout, and stream to server. `--json`
        // owns stdout for the event protocol, so it opts out of the tee.
        stream_stdin(transport, &running, !args.json)?;

        if !args.json {
            eprintln!("End of transmission.");
        }
        0
    } else {
        // Script mode - prose goes to stdout. The interactive niceties
        // only make sense for a human on a TTY; scripts and agents get
        // the JSON contract (or nothing) instead.
        if !args.json {
            if io::stdout().is_terminal() && (size.rows > 30 || size.cols > 160) {
                println!("Current terminal size is {}x{}.", size.rows, size.cols);
                println!("It's too big to be viewed on smaller screens.");
                println!("You can resize it anytime.");
            }

            let mut stdout = io::stdout();
            let show_qr = stdout.is_terminal();
            emit_human_sharing_message(&mut stdout, &share_url, show_qr);
        }

        // Run script mode with PTY. The share URL and room ride into the
        // shell's environment so `shellshare status` can recover the link.
        let session = SessionEnv {
            url: &share_url,
            room: &room,
        };
        let code = script::run_script_mode(transport, &running, args.exec.as_deref(), &session)?;

        if !args.json {
            println!("End of transmission.");
        }
        code
    };

    if args.json {
        // PTY output is raw bytes and may leave stdout mid-line; start
        // the event on a fresh line so it stays parseable as a whole line
        if !stream_mode {
            println!();
        }
        emit_json(&serde_json::json!({
            "event": "end",
            "exit_code": exit_code,
        }));
    }

    Ok(exit_code)
}

/// Translate lone LF into CRLF, writing the result into `out`.
///
/// A raw pipe delivers a log's Unix `\n` line endings, but the viewer is a
/// terminal emulator (xterm.js) where `\n` is a line feed - cursor down, same
/// column - and only `\r` returns to column 0. So bare LFs render as a
/// staircase. A shell session gets `\n` -> `\r\n` for free from the PTY's
/// ONLCR; stream mode has no PTY, so we replicate it here. `prev_was_cr`
/// carries the "last byte was CR" state across chunk boundaries so an existing
/// CRLF (or a CR split across two reads) is never doubled into CR-CR-LF.
fn lf_to_crlf(input: &[u8], prev_was_cr: &mut bool, out: &mut Vec<u8>) {
    out.clear();
    for &byte in input {
        if byte == b'\n' && !*prev_was_cr {
            out.push(b'\r');
        }
        out.push(byte);
        *prev_was_cr = byte == b'\r';
    }
}

/// Stream stdin to the server: relay bytes until EOF. When `echo_stdout` is
/// set, also tee each chunk to stdout (verbatim) so the local pipeline keeps
/// working - `journalctl --follow | shellshare` still shows and forwards its
/// output. `--json` clears the flag because that mode reserves stdout for the
/// event protocol. A broken downstream pipe (e.g. `| head`) must not abort the
/// broadcast, so stdout write errors are ignored - the broadcast is the job.
///
/// Only the broadcast is normalized to CRLF (see `lf_to_crlf`); the tee stays
/// verbatim so a downstream command sees exactly what was piped in and the
/// local terminal applies its own ONLCR.
fn stream_stdin(
    mut transport: ws::Transport,
    running: &Arc<AtomicBool>,
    echo_stdout: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut buffer = [0u8; 4096];
    let mut stdout = io::stdout();
    let mut broadcast = Vec::with_capacity(buffer.len() + buffer.len() / 8);
    let mut prev_was_cr = false;

    loop {
        if !running.load(Ordering::SeqCst) {
            break;
        }

        let bytes_read = io::stdin().read(&mut buffer)?;
        if bytes_read == 0 {
            // EOF
            break;
        }
        let chunk = &buffer[..bytes_read];

        if echo_stdout {
            // Fire-and-forget: flush so `--follow` streams live; a dead
            // downstream just means the local echo stops, not the broadcast.
            let _ = stdout.write_all(chunk);
            let _ = stdout.flush();
        }

        lf_to_crlf(chunk, &mut prev_was_cr, &mut broadcast);

        let size = get_terminal_size();

        if let Err(e) = transport.send(&broadcast, size) {
            eprintln!("\r\nERROR: {e}");
            eprintln!("\rERROR: Exit shellshare and try again later.");
            // The room belongs to someone else now; it is not ours to
            // delete, so skip the shutdown cleanup
            return Ok(());
        }
    }

    transport.shutdown_and_delete();
    Ok(())
}
