//! Shellshare CLI client - Share your terminal session
//!
//! This module provides the client functionality for streaming terminal
//! output to a shellshare server.

mod crypto;
mod script;
mod ws;

use std::io::{self, IsTerminal, Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use crate::protocol::TermSize;
use rand::Rng;

/// Get the current terminal size using ioctl (TIOCGWINSZ) via `term_size`.
/// Falls back to 80x24 when not attached to a terminal.
#[allow(clippy::cast_possible_truncation)] // Terminal dimensions always fit in u16
fn get_terminal_size() -> TermSize {
    term_size::dimensions()
        .map(|(cols, rows)| TermSize {
            cols: cols as u16,
            rows: rows as u16,
        })
        .unwrap_or_default()
}

/// Client configuration arguments
pub struct ClientArgs {
    pub server: String,
    /// URL viewers should use when it differs from the broadcast URL
    /// (e.g. a tunnel in front of the local server); the share link is
    /// printed with this, while the transport still talks to `server`
    pub display_server: Option<String>,
    pub room: Option<String>,
    pub password: Option<String>,
    pub stdin: bool,
    /// Print machine-readable JSON events to stdout instead of prose
    pub json: bool,
    /// Command to run instead of an interactive shell (`shellshare exec`);
    /// the broadcast ends when it exits and its exit code is propagated
    pub exec: Option<Vec<String>>,
    /// Viewer color theme, already validated against `themes::names()`
    pub theme: Option<String>,
    /// End-to-end encrypt the broadcast (the default). When false the
    /// terminal is sent in plaintext - for viewers on plain HTTP, where
    /// browsers can't decrypt
    pub encrypt: bool,
}

/// Generate a random 18-character alphanumeric room ID
fn generate_room_id() -> String {
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = rand::thread_rng();

    // Exactly 18 chars: the viewer recognizes auto-generated ids by this
    // length to keep them out of the tab title (isAutoGeneratedRoom in
    // templates/room.html), so the length must stay in lockstep.
    (0..18)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

/// Get the default password (MAC address as integer, like Python's `uuid.getnode()`)
fn get_default_password() -> String {
    if let Ok(Some(mac)) = mac_address::get_mac_address() {
        // Convert MAC address bytes to an integer (like Python's uuid.getnode())
        let bytes = mac.bytes();
        let mut value: u64 = 0;
        for &byte in &bytes {
            value = (value << 8) | u64::from(byte);
        }
        value.to_string()
    } else {
        // Fallback to a random value if MAC address is unavailable
        let mut rng = rand::thread_rng();
        rng.gen::<u64>().to_string()
    }
}

/// Whether browsers will treat the share link as a secure context.
/// `WebCrypto` (which the viewer needs to decrypt) only exists on https
/// pages, localhost, and loopback addresses.
///
/// Sibling loopback logic lives in `main.rs`'s `serve()`, but operates
/// on the raw `--host` arg (no scheme, plus wildcard detection), so the
/// two intentionally don't share a parser - keep their notions of
/// "loopback" consistent if either changes.
fn is_secure_context_url(base: &str) -> bool {
    let Some(rest) = base.strip_prefix("http://") else {
        return true; // https
    };
    let authority = rest.split('/').next().unwrap_or(rest);
    // Strip the port; IPv6 hosts are bracketed in URLs
    let host = authority.strip_prefix('[').map_or_else(
        || authority.rsplit_once(':').map_or(authority, |(h, _)| h),
        |h| h.split(']').next().unwrap_or(h),
    );
    let host = host.to_ascii_lowercase();
    host == "localhost"
        || host.ends_with(".localhost")
        || host
            .parse::<std::net::IpAddr>()
            .is_ok_and(|ip| ip.is_loopback())
}

/// Normalize server URL (ensure it has a scheme, strip trailing slashes)
fn normalize_server_url(server: &str) -> String {
    let server = if server.contains("://") {
        server.to_string()
    } else {
        format!("http://{server}")
    };
    server.trim_end_matches('/').to_string()
}

/// Emit one machine-readable event line on stdout (the `--json` contract:
/// whole JSON objects, one per line, flushed immediately so a pipe reader
/// sees the share URL before any terminal output follows).
fn emit_json(event: &serde_json::Value) {
    println!("{event}");
    let _ = io::stdout().flush();
}

/// Run the shellshare client. Returns the exit code to propagate: the
/// child command's status for `exec`, otherwise 0.
pub fn run(args: ClientArgs) -> Result<i32, Box<dyn std::error::Error>> {
    let server = normalize_server_url(&args.server);
    let share_base = args
        .display_server
        .map_or_else(|| server.clone(), |s| normalize_server_url(&s));
    let room = args.room.unwrap_or_else(generate_room_id);
    let password = args.password.unwrap_or_else(get_default_password);

    // Build room path (r/{room})
    let room_path = format!("r/{room}");

    // Encrypted by default. The key goes only into the printed link's
    // #fragment - browsers never send fragments, so the server cannot
    // see it. Derived from this machine and the room name, so a named
    // room keeps one reusable link across restarts. --disable-encryption
    // drops to plaintext for viewers on plain HTTP (no WebCrypto there)
    let (cipher, share_url) = if args.encrypt {
        let (cipher, key) = crypto::Encryptor::for_room(&room);
        (Some(cipher), format!("{share_base}/{room_path}#{key}"))
    } else {
        (None, format!("{share_base}/{room_path}"))
    };
    if args.encrypt {
        if !is_secure_context_url(&share_base) {
            eprintln!(
                "WARNING: viewers can only decrypt on https or localhost; \
                 the link below is plain http, so browsers will refuse. \
                 For sharing over a plain-HTTP local network, run with \
                 --disable-encryption."
            );
        }
    } else {
        eprintln!(
            "WARNING: --disable-encryption is set; this broadcast is NOT \
             encrypted, so the server and anyone on the network can read \
             the terminal."
        );
    }

    // Connecting claims the room (or fails on a password mismatch), so
    // a broadcast that can never work is reported before the terminal
    // is handed over to the shell. Failures must propagate (not exit):
    // the caller may hold a tunnel whose cleanup an exit would skip
    let size = get_terminal_size();
    let transport =
        ws::Transport::connect(&server, &room_path, &password, size, args.theme, cipher)?;

    // Ctrl+C only flips the flag; the sending thread owns the transport
    // and performs cleanup (flush, room deletion) when it stops
    let running = Arc::new(AtomicBool::new(true));
    let running_clone = running.clone();
    ctrlc::set_handler(move || {
        running_clone.store(false, Ordering::SeqCst);
    })?;

    if args.json {
        emit_json(&serde_json::json!({
            "event": "sharing",
            "url": share_url,
            "room": room,
            "server": server,
            "encrypted": args.encrypt,
        }));
    }

    let exit_code = if args.stdin {
        // Stdin mode - prose goes to stderr (stdout may be piped onward)
        if !args.json {
            eprintln!("Sharing terminal in {share_url}");
        }

        // Read from stdin and stream to server
        stream_stdin(transport, &running)?;

        if !args.json {
            eprintln!("End of transmission.");
        }
        0
    } else {
        // Script mode - prose goes to stdout. The interactive niceties
        // only make sense for a human on a TTY; scripts and agents get
        // the JSON contract (or nothing) instead.
        if !args.json {
            if io::stdout().is_terminal() && (size.rows > 30 || size.cols > 160) {
                println!("Current terminal size is {}x{}.", size.rows, size.cols);
                println!("It's too big to be viewed on smaller screens.");
                println!("You can resize it anytime.");
            }

            println!("Sharing terminal in {share_url}");
        }

        // Run script mode with PTY
        let code = script::run_script_mode(transport, &running, args.exec.as_deref())?;

        if !args.json {
            println!("End of transmission.");
        }
        code
    };

    if args.json {
        // PTY output is raw bytes and may leave stdout mid-line; start
        // the event on a fresh line so it stays parseable as a whole line
        if !args.stdin {
            println!();
        }
        emit_json(&serde_json::json!({
            "event": "end",
            "exit_code": exit_code,
        }));
    }

    Ok(exit_code)
}

/// Stream stdin to the server (for testing)
fn stream_stdin(
    mut transport: ws::Transport,
    running: &Arc<AtomicBool>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut buffer = [0u8; 4096];

    loop {
        if !running.load(Ordering::SeqCst) {
            break;
        }

        let bytes_read = io::stdin().read(&mut buffer)?;
        if bytes_read == 0 {
            // EOF
            break;
        }

        let size = get_terminal_size();

        if let Err(e) = transport.send(&buffer[..bytes_read], size) {
            eprintln!("\r\nERROR: {e}");
            eprintln!("\rERROR: Exit shellshare and try again later.");
            // The room belongs to someone else now; it is not ours to
            // delete, so skip the shutdown cleanup
            return Ok(());
        }
    }

    transport.shutdown_and_delete();
    Ok(())
}
